const cocktails = [
  {
    id: 1,
    name: "Bee's Knees",
    image: "/images/beesknees.jpeg",
    description: "Gin, Lime juice, Simple syrup",
    ingredients: ["Gin", "Lime juice", "Simple syrup"],
    price: "6€",
    hasAlcohol: true,
  },
  {
    id: 2,
    name: "Caipiroska",
    image: "/images/caipiroska.jpeg",
    description: "Vodka, Lime juice, Simple syrup",
    ingredients: ["Vodka", "Lime juice", "Simple syrup"],
    price: "9€",
    hasAlcohol: true,
  },
  {
    id: 3,
    name: "Mojito",
    image: "/images/mojito.jpeg",
    description: "Rum, Lime juice, Simple syrup, Mint leaves, Club soda",
    ingredients: [
      "Rum",
      "Lime juice",
      "Simple syrup",
      "Mint leaves",
      "Club soda",
    ],
    price: "8€",
    hasAlcohol: true,
  },
  {
    id: 4,
    name: "Blue Hawaii",
    image: "/images/bluehawaii.jpeg",
    description: "Rum, Lime juice, Simple syrup, Blue curacao, Pineapple juice",
    ingredients: [
      "Rum",
      "Lime juice",
      "Simple syrup",
      "Blue curacao",
      "Pineapple juice",
    ],
    price: "7€",
    hasAlcohol: true,
  },
  {
    id: 5,
    name: "Margarita",
    image: "/images/margarita.jpeg",
    description: "Tequila, Lime juice, Triple sec, Salt",
    ingredients: ["Tequila", "Lime juice", "Triple sec"],
    price: "5€",
    hasAlcohol: true,
  },
  {
    id: 6,
    name: "Daiquiri",
    image: "/images/daiquiri.jpeg",
    description: "Rum, Lime juice, Simple syrup",
    ingredients: ["Rum", "Lime juice", "Simple syrup"],
    price: "4€",
    hasAlcohol: true,
  },
];

export default cocktails;
